# Generated by Django 6.1.1 on 2026-10-03 12:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0006_seed_manage_approval_chains'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalChain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('applies_to_module', models.CharField(choices=[('leave', 'Leave Request')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_chains', to='tenants.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('step_order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('approval_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals.approvalchain')),
                ('approver_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to='roles.role')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='approvalchain',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_approval_chain_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.UniqueConstraint(fields=('approval_chain', 'step_order'), name='unique_step_order_per_chain'),
        ),
    ]
