# Generated by Django 6.1.1 on 2026-10-03 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('organization', '0006_employee_code_unique_per_company'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('object_id', models.UUIDField()),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='approvals.approvalchain')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_instances', to='tenants.company')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='organization.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('step_order', models.PositiveIntegerField()),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to='organization.employee')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='approvals.approvalstep')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approvals.approvalinstance')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['company', 'status'], name='approvals_a_company_ecd5bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalaction',
            constraint=models.UniqueConstraint(fields=('instance', 'step_order'), name='unique_action_per_step'),
        ),
    ]
