# Generated by Django 6.0.5 on 2026-10-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0008_seed_attendance_permissions'),
        ('roles', '0008_seed_finance_permission'),
    ]

    operations = [
    ]
