# Generated by Django 6.1.1 on 2026-10-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0009_merge_20261007_0033'),
        ('roles', '0009_merge_20261007_0042'),
    ]

    operations = [
    ]
