# Generated by Django 6.1.2 on 2026-10-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_admin',
            field=models.BooleanField(default=False),
        ),
    ]
